import streamlit as st


st.markdown("""
# Terms of Use for Event Log Extraction for Process Mining Using Large Language Models
            

_Last updated: 20.04.2025

---

Welcome to the Event Log Extraction for Process Mining Using Large Language Models (the “Service”). By accessing or using the Service, you agree to comply with and be bound by these Terms of Use. Please read them carefully. If you do not agree to these terms, you may not use the Service.

### 1. Acceptance of Terms
By using this Service, you agree to the terms and conditions laid out in this Terms of Use agreement. This agreement may be updated from time to time, and any changes will be posted here. Continued use of the Service after changes are posted constitutes acceptance of the updated terms.

### 2. Description of the Service
The Event Log Extraction for Process Mining Using Large Language Models allows users to upload or select an database file and receive responses to questions related to that database. The current version supports single-question responses per session, with plans to expand functionalities. This Service is provided by researchers from the Operations and Technology Department at Kühne Logistics University and is intended for research and informational purposes.

### 3. User Responsibilities
- **Appropriate Use:** You agree to use the Service only for lawful purposes. You are solely responsible for ensuring that any data you upload is legally yours to upload and is free of malicious code, viruses, or any content that may harm the Service or its users.
- **Data Accuracy:** You are responsible for ensuring the accuracy and relevance of the data you provide to the Service. The Service does not verify or validate the data provided by users.
- **Limited License:** You may not distribute, modify, or reproduce any part of the Service without prior written consent from the authors.

### 4. Privacy and Data Use
- **Data Processing:** By uploading data, you consent to the processing of that data to generate responses. We strive to ensure data privacy and protection, but you acknowledge that the Service is a research tool in development, and certain security limitations may apply.
- **Data Retention:** Uploaded data may be retained temporarily for research and development purposes but will not be stored permanently unless explicitly agreed upon.
- **Data Sharing:** Your data will not be shared with third parties without consent, except as required by law or for academic research purposes, in which case identifying details will be anonymized.

### 5. Limitations and Disclaimers
- **Functionality Limitation:** The Service is currently only able to respond to single questions at a time. As this is a research tool, certain features may be experimental and not yet fully reliable.
- **No Guarantee of Accuracy:** Responses generated by the Service are for informational purposes only. The authors do not guarantee the accuracy, reliability, or completeness of responses.
- **Research Use:** The Service is designed for research and experimental use only. Any insights or actions taken based on the Service’s output are at the user's own risk.
- **No Warranty:** The Service is provided "as is," with no warranties of any kind, either expressed or implied. The authors disclaim any liability for damages arising from the use or inability to use the Service.

### 6. Termination of Access
We reserve the right to terminate or restrict your access to the Service at any time, without notice, if we believe you have violated these Terms of Use or if we deem it necessary for security or maintenance reasons.


### 7. Contact Information
For questions or support regarding the Service, please contact:
- Kiran Busch: kiran.busch(at)klu.org

---

By using this Service, you confirm that you have read, understood, and agree to these Terms of Use. Thank you for using Event Log Extraction for Process Mining Using Large Language Models!

""")